# the window section are specific for 15" macbook
window:
  full_screen: False
  size: (1710, 1000) 
  position: (855,0)
  #position_string: "UR"
camera:
  background_color: "#000000"
  fps: 60
  background_opacity: 1.0
universal_import_line: "from manimlib_import_ext import *"
file_writer:
  saturation: 1.5
directories:
  # This is the main folder where videos will be saved
  output: "/Users/daniel/Movies/math"